services:
  php:
    image: devilbox/php-fpm:8.2-mods
    container_name: openmage-php
    tty: true
    user: "devilbox:devilbox"
    volumes:
      - ./magento-lts-20.12.2:/var/www
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - openmage-network
    working_dir: /var/www
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=openmage
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MAGE_IS_DEVELOPER_MODE=1
    expose:
      - "9000"  # Expor a porta 9000 para o Nginx

  nginx:
    image: nginx:latest
    container_name: openmage-nginx
    ports:
      - "80:80"  # Expor o Nginx na porta 8080
    volumes:
      - ./magento-lts-20.12.2:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Configuração do Nginx
    depends_on:
      - php
    networks:
      - openmage-network

  mysql:
    image: mysql:8.0
    container_name: openmage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openmage
    networks:
      - openmage-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openmage-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      PMA_PORT: 3306
    platform: linux/x86_64
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - openmage-network

networks:
  openmage-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
