<!DOCTYPE html>
<html lang="<?= $this->getLang(); ?>">

    <head>
        <?= $this->getChildHtml('head') ?>
    </head>

    <body class="<?= $this->getBodyClass() ?>">

    <?= $this->getChildHtml('after_body_start') ?>

    <?= $this->getChildHtml('header') ?>

    <?= $this->getChildHtml('content') ?>

    <?= $this->getChildHtml('footer') ?>
    <?= $this->getChildHtml('global_cookie_notice') ?>
    <?= $this->getChildHtml('before_body_end') ?>
    </body>
</html>
