<div class="header-container">
    <div class="header">
        <a href="<?= $this->getUrl('/') ?>" title="<?= $this->getLogoAlt() ?>" class="logo">
            <img src="<?= $this->getLogoSrc() ?>" alt="<?= $this->getLogoAlt() ?>" />
        </a>
        <div class="quick-access">
            <?= $this->getChildHtml('topLinks') ?>
        </div>
        <?= $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?= $this->getChildHtml('topMenu') ?>
