<header>
    <div class="top-bar">
        <div class="container">
            <div class="content">
                <span><i class="fa-solid fa-info-circle" aria-hidden="true"></i> Legendmc.com.br</span>
                <a href="http://discord.gg"><i class="fa-brands fa-discord"></i> Discord</a>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <div class="logo">
                <a href="<?= $this->getUrl('/') ?>" title="<?= $this->getLogoAlt() ?>" class="logo">
                    <!--                    <img src="--><?php //= $this->getLogoSrc() ?><!--" alt="--><?php //= $this->getLogoAlt() ?><!--" />-->
                    <img src="https://placehold.co/100x30@2x.png?text=LegendMC" alt="<?= $this->getLogoAlt() ?>" />
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-button-icon"><i class="fa-solid fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->getUrl('customer/account/create')?>">
                            <i class="fa-solid fa-circle-user"></i>
                            <?= $this->helper('customer')->__('Register') ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->getUrl('customer/account/login')?>">
                            <i class="fas fa-sign-in-alt"></i>
                            <?= $this->helper('customer')->__('Login') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
