<meta charset="UTF-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Site, Base">
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>" />
<title><?= $this->getTitle() ?></title>
<meta name="description" content="<?= htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?= htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?= htmlspecialchars($this->getRobots()) ?>" />

<!-- Favicon custom -->
<link rel="apple-touch-icon" sizes="57x57" href="<?= $this->getSkinUrl('images/favicon/apple-icon-57x57.png') ?>">
<link rel="apple-touch-icon" sizes="60x60" href="<?= $this->getSkinUrl('images/favicon/apple-icon-60x60.png') ?>">
<link rel="apple-touch-icon" sizes="72x72" href="<?= $this->getSkinUrl('images/favicon/apple-icon-72x72.png') ?>">
<link rel="apple-touch-icon" sizes="76x76" href="<?= $this->getSkinUrl('images/favicon/apple-icon-76x76.png') ?>">
<link rel="apple-touch-icon" sizes="114x114" href="<?= $this->getSkinUrl('images/favicon/apple-icon-114x114.png') ?>">
<link rel="apple-touch-icon" sizes="120x120" href="<?= $this->getSkinUrl('images/favicon/apple-icon-120x120.png') ?>">
<link rel="apple-touch-icon" sizes="144x144" href="<?= $this->getSkinUrl('images/favicon/apple-icon-144x144.png') ?>">
<link rel="apple-touch-icon" sizes="152x152" href="<?= $this->getSkinUrl('images/favicon/apple-icon-152x152.png') ?>">
<link rel="apple-touch-icon" sizes="180x180" href="<?= $this->getSkinUrl('images/favicon/apple-icon-180x180.png') ?>">
<link rel="icon" type="image/png" sizes="192x192"  href="<?= $this->getSkinUrl('images/favicon/android-icon-192x192.png') ?>">
<link rel="icon" type="image/png" sizes="32x32" href="<?= $this->getSkinUrl('images/favicon/favicon-32x32.png') ?>">
<link rel="icon" type="image/png" sizes="96x96" href="<?= $this->getSkinUrl('images/favicon/favicon-96x96.png') ?>">
<link rel="icon" type="image/png" sizes="16x16" href="<?= $this->getSkinUrl('images/favicon/favicon-16x16.png') ?>">
<link rel="manifest" href="<?= $this->getSkinUrl('images/favicon/manifest.json') ?>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<?= $this->getSkinUrl('images/favicon/ms-icon-144x144.png') ?>">
<meta name="theme-color" content="#ffffff">

<?= $this->getCssJsHtml() ?>
<?= $this->getChildHtml() ?>
<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getIncludes() ?>
